services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "9099:9099"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge